### ISSUE TITLE
Comportamiento backend-frontend si creador de la sala la abandona

### ISSUE THREAD

**Issue by felixozcoz** [UNIZAR-30226-2023-05/Mobile-Frontend#17]

**Comment by IkerKa** [comment]
Si el líder abandona la sala, se expulsa automáticamente a todos los miembros de la sala. Creo que lo hablamos en la reunión pero si al final se hace otra cosa avisadlo con tiempo para modificarlo. Principalmente se expulsan a todos.

**Comment by IkerKa** [comment]
Bueno no si si hay algo mas, he cerrado muy rápido jaja
