### ISSUE TITLE
Peticion al back end para el Log in en Android

### ISSUE THREAD

**Issue by pablolftw** [UNIZAR-30226-2023-05/Mobile-Frontend#3]

**Comment by felixozcoz** [comment]
Conexión establecida con éxito con la API y testeo de funciones de login conseguida.

Pruebas realizadas:

1.  Conjunto de nombres de usuarios  (email) y contraseñas válidos (ya registrados)  --> Funciona correctamente
2.  Conjunto de nombres de usuarios (email) y contraseñas inválidas  (no registrados). --> Funciona correctamente
